import type { Metadata } from "next";
import { Geist, Geist_Mono, Merriweather } from "next/font/google";
import "./globals.css";
import FloatingLines from "./components/floatingLines";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const merriweather = Merriweather({
  variable: "--font-merriweather",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Eduflow",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${merriweather.variable} antialiased`}>
        <main className="">
          <div className="fixed inset-0 z-0">
            <FloatingLines
              enabledWaves={["top", "middle", "bottom"]}
              lineCount={[10, 6, 10]}
              lineDistance={[8, 6, 4]}
              bendRadius={10.0}
              bendStrength={-0.5}
              interactive={true}
              parallax={true}
              linesGradient={["#4f46e5", "#818cf8", "#c026d3", "#e879f9"]}
            />
          </div>
          {children}
        </main>
      </body>
    </html>
  );
}
